FROM python:3.11-slim

RUN pip install --no-cache-dir \
    streamlit==1.38.0 \
    psycopg2-binary==2.9.9 \
    pandas==2.2.2

WORKDIR /app

CMD ["streamlit", "run", "app.py", \
     "--server.address=0.0.0.0", \
     "--server.port=8501", \
     "--server.headless=true"]
